version: '3.1'
services:
    postgres:
        build: phpdocker/pg
        working_dir: /application
        volumes:
            - './db:/var/lib/postgresql/data'
            - './application:/application'
        environment:
            - POSTGRES_USER=flibusta
            - POSTGRES_PASSWORD=flibusta
            - POSTGRES_DB=flibusta
        ports:
            - '27101:5432'

    webserver:
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - './application:/application'
            - './cache:/application/cache'
            - './Flibusta.Net:/application/flibusta'
            - './FlibustaSQL/lib.a.attached.zip:/application/cache/lib.a.attached.zip'
            - './FlibustaSQL/lib.b.attached.zip:/application/cache/lib.b.attached.zip'
            - './phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '27100:80'

    php-fpm:
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - './application:/application'
            - './cache:/application/cache'
            - './FlibustaSQL/lib.a.attached.zip:/application/cache/lib.a.attached.zip'
            - './FlibustaSQL/lib.b.attached.zip:/application/cache/lib.b.attached.zip'
            - './Flibusta.Net:/application/flibusta'
            - './FlibustaSQL:/application/sql'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini'
